[[redirects]]
  from = "/api/*"
  to = "http://127.0.0.1:8000/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"